In [1]:
import sys
sys.path.append('/mnt/d/ariel2/code/core/')
sys.path.append('d:/ariel2/code/core/')
sys.path.append('/kaggle/input/my-ariel2-library')
import kaggle_support as kgs
import ariel_model
import ariel_simple
import ariel_gp
import time
import numpy as np

local


In [2]:
train_data = kgs.load_all_train_data()
test_data = kgs.load_all_test_data()
kgs.debugging_mode = 1
model = ariel_gp.PredictionModel()
model.run_in_parallel = True
kgs.sanity_checks_active=True
model.train(train_data)

In [3]:
n_workers_list = [3,4,6,8]
n_threads_list = [1]
N=24

res = np.zeros((len(n_workers_list), len(n_threads_list)))
# Warmup
print(N)
#kgs.n_workers = 2
#kgs.n_threads = 1
print(len(train_data[:N]))
#model.infer(train_data[:N])
for i in range(len(n_workers_list)):
    for j in range(len(n_threads_list)):
        kgs.n_workers = n_workers_list[i]
        kgs.n_threads = n_threads_list[j]
        #print(kgs.n_threads)
        tt=time.time()
        model.run_in_parallel = (kgs.n_workers>0)
        if kgs.n_workers<=2 or kgs.n_threads<=2:
            model.infer(train_data[:N])
        res[i,j] = time.time()-tt
        print(res)

# Improve this part        
print(res)

import pandas as pd

# Create a DataFrame for nice formatting
df = pd.DataFrame(
    res,
    index=[f"{w} workers" for w in n_workers_list],
    columns=[f"{t} threads" for t in n_threads_list]
)

# Print as a table with 3 decimal places
print(df.round(3).to_string())

24
24


Processing in parallel:   0%|                                                                    | 0/24 [00:00<?, ?it/s]

local
local
SpawnPoolWorker-1 1
CUDA_VISIBLE_DEVICES= 0
local
SpawnPoolWorker-2 2
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-3 3
CUDA_VISIBLE_DEVICES= 0


Processing in parallel: 100%|███████████████████████████████████████████████████████████| 24/24 [01:29<00:00,  3.72s/it]


[[89.59347415]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]


Processing in parallel:   0%|                                                                    | 0/24 [00:00<?, ?it/s]

local
local
local
local
SpawnPoolWorker-6 6
SpawnPoolWorker-7 7
CUDA_VISIBLE_DEVICES= 0
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-5 5
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-4 4
CUDA_VISIBLE_DEVICES= 0


Processing in parallel: 100%|███████████████████████████████████████████████████████████| 24/24 [01:11<00:00,  2.99s/it]


[[89.59347415]
 [72.01500082]
 [ 0.        ]
 [ 0.        ]]


Processing in parallel:   0%|                                                                    | 0/24 [00:00<?, ?it/s]

local
local
SpawnPoolWorker-11 11
CUDA_VISIBLE_DEVICES= 0
local
local
SpawnPoolWorker-12 12
CUDA_VISIBLE_DEVICES= 0
local
SpawnPoolWorker-9 9
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-10 10
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-13 13
CUDA_VISIBLE_DEVICES= 0
local
SpawnPoolWorker-8 8
CUDA_VISIBLE_DEVICES= 0


Processing in parallel: 100%|███████████████████████████████████████████████████████████| 24/24 [00:57<00:00,  2.41s/it]


[[89.59347415]
 [72.01500082]
 [58.27366614]
 [ 0.        ]]


Processing in parallel:   0%|                                                                    | 0/24 [00:00<?, ?it/s]

local
local
SpawnPoolWorker-15 15
CUDA_VISIBLE_DEVICES= 0
local
local
local
local
SpawnPoolWorker-18 18
CUDA_VISIBLE_DEVICES= 0
local
SpawnPoolWorker-17 17
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-16 16
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-19 19
CUDA_VISIBLE_DEVICES= 0
local
SpawnPoolWorker-21 21
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-20 20
CUDA_VISIBLE_DEVICES= 0
SpawnPoolWorker-14 14
CUDA_VISIBLE_DEVICES= 0


Processing in parallel: 100%|███████████████████████████████████████████████████████████| 24/24 [00:58<00:00,  2.42s/it]


[[89.59347415]
 [72.01500082]
 [58.27366614]
 [58.62956095]]
[[89.59347415]
 [72.01500082]
 [58.27366614]
 [58.62956095]]
           1 threads
3 workers     89.593
4 workers     72.015
6 workers     58.274
8 workers     58.630


In [4]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.


In [5]:
model.bias_a

AttributeError: 'PredictionModel' object has no attribute 'bias_a'